import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Checkout from '../src/checkout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to a <a href="https://nextjs.org">Next.js Ecommerce Store!</a>
        </h1>

        <div className={styles.grid}>
          
          <div className={styles.card}>
            <h2>Product 1</h2>
            <p className='text-red-400 hover:text-blue-600'>Find in-depth information about Product 1</p>
            <button onClick={() => {
              Checkout({
              lineItems: [
                  {
                    price: '',
                    quantity: 1
                  }
                ]
              })
            }
 
            }>Buy Now</button>
          </div>

          <div className={styles.card}>
            <h2>Product 2</h2>
            <p>Find in-depth information about Product 2</p>
            <button>Buy Now</button>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
